image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
    stage: build
    script:
        - docker build -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master

build:
    stage: build
    script:
        - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
        - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

test:
    stage: test
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
        - echo "FROM $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" | cat - Dockerfile.test > temp && mv temp Dockerfile.test
        - cat Dockerfile.test
        - docker build -t "$CI_REGISTRY_IMAGE:test" -f Dockerfile.test .
        - docker run -t $CI_REGISTRY_IMAGE:test