image: docker:latest

stages:
    - build
    - test
    - deploy
    
services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
    stage: build
    script:
        - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
        - mkdir image
        - docker save "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" > image/app.tar
    artifacts:
        paths:
            - image/

test:
    stage: test
    script:
        - docker load -i image/app.tar
        - echo "FROM $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" | cat - Dockerfile.test > temp && mv temp Dockerfile.test
        - docker build -t "$CI_REGISTRY_IMAGE:test" -f Dockerfile.test .
        - docker run -t $CI_REGISTRY_IMAGE:test

deploy-master:
    stage: deploy
    script:
        - docker load -i image/app.tar
        - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE"
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master
        - dev